import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import StoreProvider from "./storeprovider"
import { ReactQueryClientProvider } from "./ReactQueryClientProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "SLTB Fleet",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
        <StoreProvider>
          <ReactQueryClientProvider>
            <body className={`${inter.className} w-full`}>{children}</body>
          </ReactQueryClientProvider>
        </StoreProvider>
    </html>
  )
}
