import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import StoreProvider from "./storeprovider"
import { ReactQueryClientProvider } from "./ReactQueryClientProvider"
import Script from "next/script"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "SLTB Fleet",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-739N1G2PN0"
        ></Script>
        <Script id="google-analytics">
          {`
           window.dataLayer = window.dataLayer || [];
           function gtag(){dataLayer.push(arguments);}
           gtag('js', new Date());
         
           gtag('config', 'G-739N1G2PN0');
          `}
        </Script>
      </head>
      <StoreProvider>
        <ReactQueryClientProvider>
          <body className={`${inter.className} w-full`}>{children}</body>
        </ReactQueryClientProvider>
      </StoreProvider>
    </html>
  )
}
